### ISSUE TITLE
Downloads only a few and fails

### ISSUE THREAD

**Issue by Cloodit** [charmparticle/tiktokget#11]
Error attached below
  ```
Traceback (most recent call last):

File "/usr/local/bin/tiktokget", line 98, in <module>
    title = driver.find_element(By.XPATH,"//span[contains(@class, 'SpanText')]").text
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //span[contains(@class, 'SpanText')]
```

**Comment by charmparticle** [comment]
This happens because tiktok puts up a captcha, which prevents the javascript that would discover new videos from doing its thing. One way would be to make the selenium part be not headless, but that would disrupt the user experience and be kind of annoying. The other way would be to use a captcha solving service, but then you'd have to pay some money to use this thing, and I'd have to figure out how to use the library.

**Comment by upintheairsheep** [comment]
> This happens because tiktok puts up a captcha, which prevents the javascript that would discover new videos from doing its thing. One way would be to make the selenium part be not headless, but that would disrupt the user experience and be kind of annoying. The other way would be to use a captcha solving service, but then you'd have to pay some money to use this thing, and I'd have to figure out how to use the library.

I believe you should just make a flag to give the browser a head for that purpose.

**Comment by charmparticle** [comment]
upgrade to the latest, and you can use the -f flag to disable headless
